package output

import (
	"fmt"
	"os"
	"strings"
	"unicode/utf8"
)

const (
	svgFontSize   = 14
	svgLineHeight = 18
	svgCharWidth  = 8 // approximate monospaced char width at 14px
	svgPadding    = 20
)

// svgDoc is the outer SVG template.
// %s args: xmlComment, width, height, width, height, descElement, bgColor, fontSize, textLines
const svgDoc = `<?xml version="1.0" encoding="UTF-8"?>
%s<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">
%s  <rect width="100%%" height="100%%" fill="%s"/>
  <style>
    .mono { font-family: "Go Mono", "Inconsolata", "Courier New", monospace; font-size: %dpx; }
  </style>
%s</svg>
`

// WriteSVG renders lines as an SVG file and writes it to path.
// bgColor and fgColor accept any CSS color value ("black", "#FF0000", etc.).
// If meta has content, an XML comment and <desc> element are embedded.
func WriteSVG(path string, lines []string, bgColor, fgColor string, meta Metadata) error {
	if bgColor == "" {
		bgColor = "black"
	}
	if fgColor == "" {
		fgColor = "white"
	}

	plainLines := make([]string, len(lines))
	for i, l := range lines {
		plainLines[i] = stripANSI(l)
	}

	maxChars := 0
	for _, l := range plainLines {
		if n := utf8.RuneCountInString(l); n > maxChars {
			maxChars = n
		}
	}

	width := maxChars*svgCharWidth + svgPadding*2
	height := len(plainLines)*svgLineHeight + svgPadding*2
	if width < svgPadding*2 {
		width = svgPadding * 2
	}
	if height < svgPadding*2 {
		height = svgPadding * 2
	}

	var textLines strings.Builder
	for i, line := range plainLines {
		x := svgPadding
		y := svgPadding + (i+1)*svgLineHeight
		textLines.WriteString(fmt.Sprintf(
			"  <text x=%q y=%q fill=%q class=\"mono\" xml:space=\"preserve\">%s</text>\n",
			fmt.Sprint(x), fmt.Sprint(y), fgColor, xmlEscape(line),
		))
	}

	xmlComment := ""
	descElement := ""
	if meta.hasContent() {
		toolInfo := fmt.Sprintf("charmascii %s (%s)", meta.Version, meta.URL)
		xmlComment = fmt.Sprintf("<!-- Generated by %s -->\n<!-- Command: %s -->\n",
			xmlEscape(toolInfo), xmlEscape(meta.Command))
		descElement = fmt.Sprintf("  <desc>Generated by %s. Command: %s</desc>\n",
			xmlEscape(toolInfo), xmlEscape(meta.Command))
	}

	svg := fmt.Sprintf(svgDoc,
		xmlComment,
		width, height, width, height,
		descElement,
		bgColor,
		svgFontSize,
		textLines.String(),
	)

	return os.WriteFile(path, []byte(svg), 0o644)
}

// xmlEscape escapes characters that are not valid in SVG text content.
func xmlEscape(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}
