package output

import (
	"fmt"
	"os"
	"strings"
)

// WriteTXT writes plain text (all ANSI codes stripped) to path.
// If meta has content, a commented header block is prepended.
func WriteTXT(path string, lines []string, meta Metadata) error {
	plain := make([]string, len(lines))
	for i, l := range lines {
		plain[i] = stripANSI(l)
	}

	var header string
	if meta.hasContent() {
		header = fmt.Sprintf("# Generated by charmascii %s (%s)\n# Command: %s\n#\n",
			meta.Version, meta.URL, meta.Command)
	}

	content := header + strings.Join(plain, "\n") + "\n"
	return os.WriteFile(path, []byte(content), 0o644)
}
